name: Code check

on:
  pull_request:
    branches: ['*']

jobs:
  code-check:
    runs-on: ubuntu-latest
    name: Code check
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up Node.js environment
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify the Node.js version

      # Install yarn
      - name: Install yarn
        run: npm install --global yarn

      # Cache yarn dependencies
      - name: Setup yarn cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run linter
      - name: Run linter
        run: yarn lint

      # Check code formatting
      - name: Check code formatting
        run: yarn format:check

      # Check types
      - name: Check types
        run: yarn check-types
